image: mreichelt/android:29

before_script:
  - chmod +x ./gradlew


stages:
  - build

build: 
    stage: build 
    script:
    - ./gradlew assembleDebug
    artifacts:
       paths:
       - app/build/outputs/
