version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run all checks
          command: ./gradlew clean test
      - run:
          name: Run UI tests
          commands:
          - emulator -avd circleci-android22 -no-audio -no-window:
          background: true
          parallel: true
          # wait for it to have booted
          - circle-android wait-for-boot
    # unlock the emulator screen
          - sleep 30
          - adb shell input keyevent 82
    # run tests  against the emulator.
          - ./gradlew connectedAndroidTest -PdisablePreDex
    # copy the build outputs to artifacts
          - cp -r app/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
          - p -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Initial build
          command: ./gradlew clean assembleDebug --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - store_test_results:
          path: app/build/test-results   




