version: 2
jobs:
  build:
    working_directory: ~/foodger
    docker:
        - image: circleci/openjdk:8-jdk
        script:
        - ./gradlew assembleDebug
        artifacts:
           paths:
           - app/build/outputs/


  pages:
    script:
    - ./gradlew dokka 
    - mv app/build/doc/app/ public/
    artifacts:
       paths:
        - public

