image: mreichelt/android:29
  
jobs:
  build: 
      stage: build 
      script:
      - ./gradlew assembleDebug
      artifacts:
         paths:
         - app/build/outputs/


  pages:
    stage: deploy
    script:
    - ./gradlew dokka 
    - mv app/build/doc/app/ public/
    artifacts:
       paths:
        - public

