image: circleci/openjdk:8-jdk

version: 2
jobs:
  build: 
      script:
      - ./gradlew assembleDebug
      artifacts:
         paths:
         - app/build/outputs/


  pages:
    script:
    - ./gradlew dokka 
    - mv app/build/doc/app/ public/
    artifacts:
       paths:
        - public

